import {
    Button,
    ComboBox,
    LineEdit,
    CheckBox,
    VerticalBox,
    HorizontalBox,
    ProgressIndicator,
} from "std-widgets.slint";
export component MainWindow inherits Window {
    width: 600px;
    height: 300px;

    in property <[string]> combo_options: [];
    in property <string> select_device_error: "";
    in property <string> space_to_leave_error: "";

    in property <int> total_bytes: 0;
    in property <int> sent_bytes: 0;
    in property <string> progress_message: "";
    property <float> progress: total_bytes > 0 ? sent_bytes * 1.0 / total_bytes : 0.0;

    callback refresh_clicked();
    callback write_clicked(string, int, bool);

    VerticalBox {
        spacing: 16px;
        VerticalLayout {
            Text {
                text: "Select device to use";
            }

            HorizontalLayout {
                spacing: 8px;
                device_combo := ComboBox {
                    model: root.combo_options;
                }

                Button {
                    text: "🔄 Refresh";
                    accessible-label: "Refresh";
                    clicked => {
                        root.refresh_clicked();
                    }
                }
            }

            if root.select_device_error != "": Text {
                text: root.select_device_error;
            }
        }

        property <string> space_to_leave: "";

        VerticalLayout {
            Text {
                text: "Space to leave";
            }

            input := LineEdit {
                text <=> space_to_leave;
            }

            if root.space_to_leave_error != "": Text {
                text: space_to_leave_error;
            }
        }

        keep_local_checkbox := CheckBox {
            text: "Keep local filler file after write";
        }

        Button {
            text: "Write to device";
            clicked => {
                root.write_clicked(space_to_leave, device_combo.current-index, keep_local_checkbox.checked)
            }
        }

        VerticalLayout {
            Text {
                visible: root.progress_message != "";
                text: root.progress_message;
            }

            ProgressIndicator {
                progress: root.progress;
            }
        }
    }
}
