import {
    Button,
    ComboBox,
    LineEdit,
    CheckBox,
    VerticalBox,
    HorizontalBox,
} from "std-widgets.slint";
export component MainWindow inherits Window {
    width: 400px;
    height: 300px;

    in property <[string]> combo_options: [];
    in property <string> select_device_error: "";
    in property <string> space_to_leave_error: "";

    callback refresh_clicked();
    callback write_clicked(string, int, bool);

    VerticalBox {
        spacing: 16px;
        VerticalLayout {
        Text {
            text: "Select device to use";
        }

        HorizontalLayout {
            device_combo := ComboBox {
                width: 300px;
                model: root.combo_options;
                current-index: -1;
            }

            Button {
                text: "🔄 Refresh";
                accessible-label: "Refresh";
                clicked => {
                    root.refresh_clicked();
                }
            }
        }

        if root.select_device_error != "" : Text {
            text: root.select_device_error;
        }}

        property <string> space_to_leave: "";

        VerticalLayout {
        Text {
            text: "Space to leave";
        }

        input := LineEdit {
            text <=> space_to_leave;
        }
        if root.space_to_leave_error != "" : Text {
            text: space_to_leave_error;
        }
    }

        keep_local_checkbox := CheckBox {
            text: "Keep local filler file after write";
        }

        Button {
            text: "Write to device";
            clicked => {
                root.write_clicked(space_to_leave, device_combo.current-index, keep_local_checkbox.checked)
            }
        }
    }
}
